### ISSUE TITLE
MaxTime does not allow to set it after "23:59:59"

### ISSUE THREAD

**Issue by davidbejarcaceres** [wojtekmaj/react-time-picker#105]
## Problem, cannot use the component out of the "24:00:00" format:
I want to use this component as a Duration component, it means it takes values between "00:00:00"-"23:59:59", but also values out of the 24H format, if a duration of 28 hours is used, value = "28:00:00", and maxTime="50:00:00", the component will display the right value, but when using the arrowKeys to change does not work, only keyDown in hours input, and sets it to "23:00:00" instead of "27:00:00", also while minutes or seconds are changing with arrow keys, no onChange event is triggered, so I can not detect any changes of the input.

#### Expeted:
1.  Component with props: value="28:00:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", keyDown to reduce one hour.
3. onChange triggered with new value "27:00:00"

#### Problem:
1.  Component with props: value="28:00:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", keyDown to reduce one hour.
3. onChange triggered with value "23:00:00" instead of "27:00:00"

#### Expeted:
1.  Component with props: value="28:00:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", keyUp to add one hour.
3. onChange triggered with new value "29:00:00"

#### Problem:
1.  Component with props: value="28:00:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", keyDown to reduce one hour.
3. onChange never triggered and value does not goes to "29:00:00".

#### Expeted:
1.  Component with props: value="00:05:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", type 48 to set it to "48:05:00"
3. onChange triggered with new value "48:05:00"

#### Problem:
1. Component with props: value="00:05:00", maxTime="50:00:00", format="HH:mm:ss".
2. While focus on "hour group", type 48 to set it to "48:05:00"
3. onChange triggered after first key pressed for hours with value "04:05:00".
4. Hour group focus lost and moved to minutes group.

**Comment by wojtekmaj** [comment]
There's simply no such hour, and [input type="time"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) which this component attempts to emulate (and uses under the hood for browsers supporting it) would not accept anything above 23:59:59.
