### ISSUE TITLE
Bug with minTime when changing AM/PM

### ISSUE THREAD

**Issue by bennyfink** [wojtekmaj/react-time-picker#106]
Bug Behavior:
1. Set minTime to 8:01am
2. Set value to 8:00am (via prop)
3. use am/pm UI to change time to 8:01pm

An onChange event should be sent but is not, and the minute field remains in an invalid state.

Does react-time-picker always assume the value prop is after minTime?

**Comment by wojtekmaj** [comment]
Yes, it currently does. It does not allow sending any invalid times through onChange, nor it won't accept them from props.
