### ISSUE TITLE
clearIcon and clockIcon should take null as a parameter

### ISSUE THREAD

**Issue by Cloud11PL** [wojtekmaj/react-time-picker#107]
According to the #7  issue `null` has to be passed as a parameter to `clearIcon` and `clockIcon` what causes type errors in TypeScript as the parameters doesn't accept `null` type.

Example code:

              <TimePicker
                onChange={setTimeValue}
                value={timeValue}
                locale={LOCALE}
                clearIcon={null}
                clockIcon={null}
                disableClock
                format="hh:mm a"
              />

**Comment by wojtekmaj** [comment]
Everything is fine in the component, it's the typings which are wrong. Feel free to contribute in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.
