### ISSUE TITLE
TimeInput should take (and use) a ref prop

### ISSUE THREAD

**Issue by billsaysthis** [wojtekmaj/react-time-picker#108]
This is needed for use with common validation libs, e.g., Yup with React-Hook-Form. (Happy to provide additional info but not sure what that might be, this seems pretty self-explanatory...)

**Comment by wojtekmaj** [comment]
Every React component takes `ref` prop. I suppose you mean that `ref` prop should point to something else than TimeInput component itself?

This would be a breaking change for sure to begin with.

What, in your opinion, `ref` should be pointing to? Main `div`? Native hidden `input[type="time"]`?

**Comment by billsaysthis** [comment]
This might be an issue more with the types for RTP (which I know you don't work on or approve), but in our case the ref needs to point to whatever has the current time value as it would be used for react-hook-form validators.
