### ISSUE TITLE
How can I get AM/PM value?

### ISSUE THREAD

**Issue by mitaxe** [wojtekmaj/react-time-picker#109]
How can I get AM/PM value? 
onChange only returns a time value, but without am/pm.

**Comment by wojtekmaj** [comment]
onChange should always return 24h value for the sake of consistency with Date().

**Comment by mitaxe** [comment]
The workaround I found was to find select directly in DOM and get the value, but it's a hack, maybe there exists an alternative which library provides?

**Comment by wojtekmaj** [comment]
You can use these utils to achieve 12 hour format.

https://www.github.com/wojtekmaj/react-time-picker/tree/master/src%2Fshared%2Fdates.js
