### ISSUE TITLE
Disable icon clock when disableClock is defined as true

### ISSUE THREAD

**Issue by ivanfr90** [wojtekmaj/react-time-picker#11]
Hi!

I've see that the in last version the property `disableClock` has been added, I appreciate it!!
So, a detail that I've seen is that if you specifies `disableClock` as **true**, an useless icon clock continues showing in picker. I consider that if you disable the clock, icon should not be shown and the property `clockIcon` should be ignored.

Thank you!!

**Comment by wojtekmaj** [comment]
There you go, fixed ;)
