### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by mroutadi** [wojtekmaj/react-time-picker#110]
Hi, I tried to import react-time-picker to my project that i get this error:

`error - ./node_modules/react-time-picker/dist/TimePicker.css`
`Global CSS cannot be imported from within node_modules`
`Read more: https://err.sh/next.js/css-npm`
`Location: node_modules\react-time-picker\dist\entry.js`

**Comment by wojtekmaj** [comment]
Import React-Time-Picker without the styles (see README) and import styles manually yourself.
