### ISSUE TITLE
The input for Hours, Minutes and Seconds not working on Firefox with two digit

### ISSUE THREAD

**Issue by guruprasanth5** [wojtekmaj/react-time-picker#112]
The input for Hours, Minutes and Seconds do not work if it has 2 digits and if there is a selection on it.

![Screenshot from 2021-03-08 12-54-13](https://user-images.githubusercontent.com/11155063/110288042-6e656100-800d-11eb-8309-4e5b8572a633.png)

In the above screenshot i am trying to edit the seconds and i am not able to change it in Firefox.
Version: 78.4.0esr (64-bit)

**Comment by billsaysthis** [comment]
Duplicate of #92
