### ISSUE TITLE
Clock does not work for german locale "de-De"

### ISSUE THREAD

**Issue by stefaneidelloth** [wojtekmaj/react-time-picker#123]
<TimePicker
                    value={this.__departureDate}
                    onChange={() => {
                          this.inputChanged();
                    }}
                    locale="de-De"
                  />

![image](https://user-images.githubusercontent.com/12675339/126509992-44f2cc4a-07e3-4dae-9784-3619c8f2a459.png)

Edit: Does not seem due to local? Need some more time to inspect.

**Comment by wojtekmaj** [comment]
`de-De` is not a valid locale. Try `de-DE`.
