### ISSUE TITLE
Minute Increments

### ISSUE THREAD

**Issue by github-jeff** [wojtekmaj/react-time-picker#124]
Is it possible to limit the minute increments to the nearest 15 minute choice?  For example if user puts in 5:10PM it will increment to 5:15PM?

**Comment by wojtekmaj** [comment]
It's not possible, but it definitely should! That's a great idea.

**Comment by ivan-sakoman** [comment]
is there a possibility to enable increments by 15minutes? or is there a plan to implement that functionality in the future?

**Comment by wojtekmaj** [comment]
Duplicate of #55
