### ISSUE TITLE
Does onChange always return a string?

### ISSUE THREAD

**Issue by nikhil-bhandari** [wojtekmaj/react-time-picker#128]
Hi,

I noticed in the documentation that `value` can be a `Date` or `string`, but the value received in `onChange` is always a string?

**Comment by DavidPx** [comment]
I'll comment that the `@types/react-time-picker` typings are misleading.  They imply that `onChange`'s event will match that of `value`.

```
    /**
     * Input value.
     */
    value: T;

     * Function called when the user picks a valid time.
     */
    onChange?: ((value: T) => void) | undefined;
```
