### ISSUE TITLE
Feature request: Add prop to nullify value when invalid

### ISSUE THREAD

**Issue by fbrcc** [wojtekmaj/react-time-picker#13]
Hello, thanks so much for your work with react-time-picker :)
I'm running in a situation where when the user inputs an invalid time (for example: 1:80 am), the minute input appears red, but my wrapping form receives the valid time of 1:08 am (the last valid time which triggered the onChange function) behind the scenes. 

I understand calling onChange only on valid times is the current desired behavior, but I think a prop to nullify the whole value on invalid dates would be useful. Let me know if I can help out.

Ive seen on other issues that you're adding the option for listeners. I think that's a good idea, but still, I think a prop to nullify invalid times (returning null like when erasing time) would be useful even if listeners exist.

**Comment by wojtekmaj** [comment]
Closer to native behavior would be to prevent the invalid values altogether, and this is the direction I'd like to go in with this package, but your suggestion is something that would certainly come useful to a lot of people, thanks!
