### ISSUE TITLE
OnChange does not correctly capture invalid minutes value when re entered 

### ISSUE THREAD

**Issue by mikeghealth** [wojtekmaj/react-time-picker#130]
**STR:**

1. enter a time with invalid minutes say '08:88 AM' everything is fine as onChange does not trigger when it is invalid in this case
2.  however click on minutes section and enter '77' all of a sudden onChange triggers and now the time says it's '08:07' a valid time, but not what the user entered. This causes a seemingly invalid time, to pass validation 

Please see attached, me entering a valid time, then re entering an invalid time and having it show up as just the first digit. e.g. '08:77" becomes '08:07'

https://user-images.githubusercontent.com/45187590/143147015-e9efae4c-227c-4d46-9779-9fef9c8636d9.mov

**Comment by wojtekmaj** [comment]
Before an invalid value "77" was entered, a perfectly valid "7" must have been entered first. As the last valid value, 8:07 gets accepted here.

**Comment by Roman-ZN** [comment]
Hello @wojtekmaj 
Thank you for this great lib. However, looks like this is a bug. We need to have the ability to override invalid values, for example, if the user enters 66 minutes, the system should be able to override to 06, as it implemented in html <input type="time" />.
