### ISSUE TITLE
Hour input doesn't handle fast typing well, and converts input to unintended value

### ISSUE THREAD

**Issue by zachandblue** [wojtekmaj/react-time-picker#131]
Type "345" into the hours input quickly, as if one were typing 3:45.    Instead of '3' going into the hours input field, and '45' going into the minutes input field, the result is "10:05".

**Comment by wojtekmaj** [comment]
Yep that's a bug.

We change focus on key up, and you can press next key (in this case: "4") down before the previous one (in this case: "3") is up. This results in "34" typed in a number input, which for gets "converted" to 24-hour time format, removing 24 hours, resulting in "10" in hour field.

**Comment by DSp4wN** [comment]
I tried typing zero and nine but the 0 gets immediately converted to 12 creating a problem in typing the single digit hour with zero
