### ISSUE TITLE
Next.js doesn't allow importing CSS files

### ISSUE THREAD

**Issue by neaorin** [wojtekmaj/react-time-picker#133]
Trying to use TimePicker in a [Next.js](https://nextjs.org/) project, I get the following error:

**Failed to compile**

../../node_modules/react-clock/dist/Clock.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ..\..\node_modules\react-time-picker\dist\entry.js

Is it possible to ship a compiled version of Clock.css?

Thank you.

**Comment by wojtekmaj** [comment]
In Next.js, you'd need to import CSS yourself by following these instructions:

https://github.com/wojtekmaj/react-time-picker#custom-styling

Or don't import CSS at all and create your own styles as you like.
