### ISSUE TITLE
onChage only triggers with valid values.

### ISSUE THREAD

**Issue by ioness** [wojtekmaj/react-time-picker#136]
Say you have value: "14:23".

Then the user removes 14, so input displays: "--:23"

If for example you have required={true}, you will see a highligh in -- but internally, the value is still 14:23 as onChange only executes when a valid value is provided...

I think it should be null, otherwise how can we stop the formulary from working? It is not displaying the real value.

What do you think?

**Comment by DavidPx** [comment]
I also think that this is a bug...  how would I disable my "Save" button when the user deletes the value?
