### ISSUE TITLE
AM/PM selector is visible on a locale which is 24 hour (bg-BG)

### ISSUE THREAD

**Issue by plamenh** [wojtekmaj/react-time-picker#14]
Clock is ok and it is in 24 hour format. But we still get the AM/PM picker which, instead of 'AM' and 'PM' options shows a strange single '21 ч.' select option. 'ч.' is short for 'hours' in bg-BG.

Bug maybe?

**Comment by wojtekmaj** [comment]
Fixed in v3.6.0 (I think - can't pinpoint the exact fix right now, possibly fixed with #25).
