### ISSUE TITLE
[MOBILE][BUG] - AM/PM dropdown option on the middle of screen

### ISSUE THREAD

**Issue by jcpaesf** [wojtekmaj/react-time-picker#145]
When we select the AM/PM option on mobile devices, the dropdown shows on the middle of the screen

<img width="440" alt="image" src="https://user-images.githubusercontent.com/50344703/188650386-6e762ab5-77c0-476b-a877-5bfe66bc94a0.png">

**Comment by wojtekmaj** [comment]
Looks like a browser bug to me (or rather: a dev tools emulator bug), nothing we can do about this.
