### ISSUE TITLE
Typing zero and nine gets immediately converted to 12

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-time-picker#146]
I tried typing zero and nine but the 0 gets immediately converted to 12 creating a problem in typing the single digit hour with zero

_Originally posted by @DSp4wN in https://github.com/wojtekmaj/react-time-picker/issues/131#issuecomment-1245841231_

**Comment by wojtekmaj** [comment]
Duplicate of #93

**Comment by dev-bre** [comment]
any chance you could address this issue?
