### ISSUE TITLE
Demo page 403

### ISSUE THREAD

**Issue by juicylevel** [wojtekmaj/react-time-picker#147]
![Снимок](https://user-images.githubusercontent.com/16361045/190347216-73ccfbac-1614-4250-8aef-71754a9ae4ac.PNG)
![Снимок2](https://user-images.githubusercontent.com/16361045/190347232-4f6418ae-e478-42d1-a86f-56f0991eb751.PNG)

**Comment by wojtekmaj** [comment]
Russian/Belarussian traffic is blocked.
