### ISSUE TITLE
I can't set maxLength for setting hours and minutes.

### ISSUE THREAD

**Issue by alexpetrus20** [wojtekmaj/react-time-picker#15]
Hi, I am using react time picker and I want to add a limit for the input to add only two numbers for hours and two numbers for minutes.

**Comment by wojtekmaj** [comment]
See #29 - while technically there's no max length, user will be pushed to the next field when they obviously can't add another digit, so typing "1" in hour field would allow user to type another number (to write hour like 11), and typing "4" would push user to the next field (there's no 4x hour).

**Comment by wojtekmaj** [comment]
With 6377396 this should no longer be an issue.
