### ISSUE TITLE
Hours input also taking 24,25...,29 values

### ISSUE THREAD

**Issue by kinjaldave-tech** [wojtekmaj/react-time-picker#150]
Hours input also taking 24,25...,29 values. Its not taking 30 and more than that. Also in minutes its taking upto 99. I have set locale ="sv-sv" Please help.

**Comment by cemysf** [comment]
+1

I also need to track/edit how much time a process runs for, therefore need the ability of putting arbitrary values in hours field, e.g. `67h, 54m 33s` is it possible with this library?

**Comment by wojtekmaj** [comment]
> Hours input also taking 24,25...,29 values. Its not taking 30 and more than that. Also in minutes its taking upto 99. I have set locale ="sv-sv" Please help.

Just checked and it seems like it's not the case, `min`/`max` attribute values are set correctly, and we have unit tests for that. Is there something I'm missing?

Note that you may be able to write invalid input, somehow - but it won't result in an invalid timestamp to be returned.

**Comment by wojtekmaj** [comment]
> I also need to track/edit how much time a process runs for, therefore need the ability of putting arbitrary values in hours field, e.g. 67h, 54m 33s is it possible with this library?

Unrelated, but no.

**Comment by kinjaldave-tech** [comment]
> > Hours input also taking 24,25...,29 values. Its not taking 30 and more than that. Also in minutes its taking upto 99. I have set locale ="sv-sv" Please help.
> 
> Just checked and it seems like it's not the case, `min`/`max` attribute values are set correctly, and we have unit tests for that. Is there something I'm missing?
> 
> Note that you may be able to write invalid input, somehow - but it won't result in an invalid timestamp to be returned.

Thanks for the reply.
It was also converting 24,25,..29 to invalid/undefined value or randomly values like 02:00 like that..
Also i was using this in my project for start time & end time, but i kept starting time not required but end time required, And if i was not setting any value in start time it automatically send invalid/undefined value.
