### ISSUE TITLE
How to get the keycode of the pressed key

### ISSUE THREAD

**Issue by JeanDevonne** [wojtekmaj/react-time-picker#204]
I try to capture the event of the enter key to call a function that adds the value of the input and continue adding more elements without the need to press the + icon.

Is there a way to handle keypress events?

![image](https://user-images.githubusercontent.com/5619799/208777201-53de5f30-62fa-422e-a80a-3ea9b3f61ba8.png)

**Comment by wojtekmaj** [comment]
You can totally pass any event prop you like to React-Time-Picker, including onKeyPress.
