### ISSUE TITLE
Npm installed but cannot use.

### ISSUE THREAD

**Issue by Junior2Ran** [wojtekmaj/react-time-picker#22]
The browser console report error :
` Uncaught [ModJS] Cannot find module 'node_modules/react-time-picker/dist/Clock.css' `

But i found the node_modules folder has the file `node_modules/react-time-picker/dist/Clock.css` , and the path is correct.

Why did it happen ?

**Comment by wojtekmaj** [comment]
It looks like you have a problem with some external tool, perhaps ModJS that is throwing the error in the first place?

I'm afraid I won't be able to help you; I simply lack the knowledge about this tool. I suggest writing that to ModJS support instead. Wish you luck!
