### ISSUE TITLE
Leading 0 on the minutes shows up far away from the number

### ISSUE THREAD

**Issue by dev-bre** [wojtekmaj/react-time-picker#229]
I am experiencing issues with my design where the leading 0 shows up far away from the actual minute value. 
for now I am just hiding it, but the I would like to see the leading 0, how to fix this?

**Comment by wojtekmaj** [comment]
It's likely that your custom styles are somehow interfering with the defaults I provide for the React-Time-Picker. You will need to add a bit of custom styling yourself.
