### ISSUE TITLE
AM/PM not selectable when locale="ar-ae"

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#25]
When I set the locale to "ar-ae" (Arabic United Arab Emirates) or "ar" (Arabic), the am/pm selector is not available, it just shows the م character. I'm also not able to enter numbers above 12. So effectively you can only choose times in the second half of the day.

<img width="221" alt="Screen Shot 2019-06-05 at 3 34 07 PM" src="https://user-images.githubusercontent.com/4451556/58984918-32ea9280-87a8-11e9-96ee-093da56f978b.png">

The first TimePicker has the locale set to "ar-ae" and the second is set to "fa-IR".

**Comment by wojtekmaj** [comment]
Thank you for your time reporting this!

I created a fix and it should be available with the next release.

**Comment by wojtekmaj** [comment]
Does that look right to you? 

<img width="188" alt="obraz" src="https://user-images.githubusercontent.com/5426427/59022084-6a5f4a80-884d-11e9-9a01-1755722965ea.png">

**Comment by emilyuhde** [comment]
That looks good, I think! ص should be am and م should be pm, I believe.

**Comment by wojtekmaj** [comment]
Just a heads-up - React-Time-Picker `v3.6.0` was released a few moments ago and includes the fix for this issue.
