### ISSUE TITLE
Unable to resolve "react-time-picker/dist/TimePicker.css" from "components/MentorRegister/FormikRegister.js"

### ISSUE THREAD

**Issue by rasangalk** [wojtekmaj/react-time-picker#276]

**Comment by wojtekmaj** [comment]
Well you didn't provide much info, so all I can say, is that it sounds like a problem on your side: problem with resolver, using old react-time-picker version... Can't tell.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5426427/227136656-cd9a85c3-f94d-45e6-aeab-bba94802215a.png">
