### ISSUE TITLE
Focus jumps from hours field to seconds field, missing the minutes field.

### ISSUE THREAD

**Issue by IndraManickam** [wojtekmaj/react-time-picker#282]
When a user is typing values rapidly on the input field. the key-up event is fired rapidly.
The key-up function shifts the focus to the next field.  As a result, the key-up event that is later fired will consider the next field as the minute field.

Steps to reproduce.
1. Rapidly type 12 in the hour field.
2. Minute field should have a value more than or equal to 6.

Having a Scheduling logic before calling the focus will prevent the racing scenario between the user key-up event and the focus function.

**Comment by IndraManickam** [comment]
@wojtekmaj  can you pls review the defect and the PR attached.

**Comment by IndraManickam** [comment]
@wojtekmaj any updates?

**Comment by wojtekmaj** [comment]
Duplicate of #131
