### ISSUE TITLE
Text Color Inconsistencies

### ISSUE THREAD

**Issue by Jib-Abdel** [wojtekmaj/react-time-picker#286]
Hello, I am attempting to use this module alongside my thematic User Interface. However, there's seems to be an inconsistency in the TimePicker.CSS file. This class: .react-time-picker__inputGroup__input is causing an inconsistency where the colors of the text is not inline with the rest of my form. However, within the similar class: react-time-picker__inputGroup__input--hasLeadingZero, this issue does not exist. I found that changing the CSS of .react-time-picker__inputGroup__input will resolve the issue. All it requires is the color property to be set to the current documents color. Here is a screen shot demonstrating the problem: 
![Screenshot (19)](https://user-images.githubusercontent.com/107577845/229626678-a87ad326-3d23-43ec-8573-e7d4fe6f5ee0.png)
![Screenshot (21)](https://user-images.githubusercontent.com/107577845/229626679-64efd557-e6db-4b75-97b7-85b6bc0b03c3.png)
![Screenshot (18)](https://user-images.githubusercontent.com/107577845/229626682-0ee946e4-98bb-4271-9867-0aec4e43d1ff.png)

**Comment by Jib-Abdel** [comment]
#288

**Comment by Jib-Abdel** [comment]
Please review this PR

**Comment by wojtekmaj** [comment]
Fixed in#288
