### ISSUE TITLE
French Canadian (locale="fr-CA") shows both 24 and 12 hour inputs

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#30]
I set the locale to locale="fr-CA" on the TimePicker I'm using and it shows the 24 hour input, 12 hour input, and then the minute input. I believe French speaking Canada uses the 24 hour clock (https://www.btb.termiumplus.gc.ca/redac-chap?lang=eng&lettr=chapsect1&info0=1.1.12) No AmPm select is shown, just the extra 12 hour input.

<img width="494" alt="Screen Shot 2019-06-12 at 1 38 14 PM" src="https://user-images.githubusercontent.com/4451556/59373283-5f0d9280-8d17-11e9-8175-b36ce05298c1.png">

**Comment by wojtekmaj** [comment]
Thanks for reporting this!

fr-CA time is formatted by Google Chrome as "21 h 13" instead of typical "21:13". After the time is formatted using a given locale, it is parsed and React-Time-Picker figures out what's what - and we end up with "H h mm" format, which causes this problem.

**Comment by emilyuhde** [comment]
I just upgraded to 2.6.0 and unfortunately I still see this issue happening. Did your commit you made related to this make it into the new release? @wojtekmaj

**Comment by wojtekmaj** [comment]
No, it did not, it sits on `no-input-repeat` branch. :( I was considering if decreasing flexibility by not allowing multiple inputs of the same type is a big deal or not.

**Comment by emilyuhde** [comment]
Hmm...maybe you could add in the functionality to only allow a single instance of each type of input, and have it be set with a prop. So it could default to how it currently works, but you could add a prop to turn on that no repeat functionality, so that would prevent it potentially breaking any users who depend on the current flexibillity.

**Comment by wojtekmaj** [comment]
Another idea that came to my mind is to disallow multiple inputs of the same type, but only in default format determined by `locale` prop. I don't think that's ever going to happen with default formats. This way, users will still be able to do whatever weird shit they are up to, while fixing this issue! Yaaaay!

**Comment by wojtekmaj** [comment]
Another idea that came to my mind is to disallow multiple inputs of the same type, but only in default format determined by `locale` prop. I don't think that's ever going to happen with default formats. This way, users will still be able to do whatever they are up to, while fixing this issue! Yaaaay!

**Comment by wojtekmaj** [comment]
Fix will be out with the next release!
