### ISSUE TITLE
Warning suppression in prod mode: "Warning: Failed prop type: The prop `amPm` is marked as required in `Hour12Input`, but its value is `null`."

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#31]
Is it possible to have this warning suppressed in prod mode or offer some way to turn it off? 

If the value of the time picker is initialized to null for a 12 hour formatted time, this warning will show up in the console. The warning makes sense, but I don't want the warning all the time, especially for a non-required time picker.

<img width="1076" alt="Screen Shot 2019-06-20 at 9 06 05 AM" src="https://user-images.githubusercontent.com/4451556/59851493-c55b6c00-933a-11e9-9738-a2dc990cb085.png">

**Comment by wojtekmaj** [comment]
Please see discussion in #24

**Comment by wojtekmaj** [comment]
Analyzed that and it turns out this wasn't really required prop. Yay!

**Comment by wojtekmaj** [comment]
Just a heads-up - React-Time-Picker `v3.6.0` was released a few moments ago and includes the fix for this issue.
