### ISSUE TITLE
Translation ability for "bad" input value messages in Firefox

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#32]
Firefox allows non-numeric characters to be input into type="number" inputs, so invalid values can be added to the hour/minute/second inputs of the time picker. This is fine, but when one of these values is entered, in Firefox a title message is displayed in English stating a warning. I set my browser language to German and the messages are still appearing in English, so it looks like they aren't auto translating based on locale. 

1. Just a question, where are the messages coming from? I searched the react-time-picker repo and didn't see the strings anywhere.
2. I need the ability to translate and/or turn off these messages for my product that's using the react-time-picker. Adding the ability to do that to the library would be very helpful.

<img width="586" alt="Screen Shot 2019-06-20 at 9 12 20 AM" src="https://user-images.githubusercontent.com/4451556/59852778-8bd83000-933d-11e9-911d-cda88318549e.png">

**Comment by wojtekmaj** [comment]
Hi,
what you are looking at is native form validation. The text you're seeing is set by the browser you're using and depends on your browser's locale.

It is possible to overwrite this behavior with your own validation methods with your own messages. I certainly like this idea, even though it's hell lot of work to get right!

**Comment by emilyuhde** [comment]
I found this post on Stackoverflow that was helpful for this, if anyone wants to override the messages themselves using `setCustomValidity`:

https://stackoverflow.com/a/5276722
