### ISSUE TITLE
Why? Errors :(

### ISSUE THREAD

**Issue by KrasnovD** [wojtekmaj/react-time-picker#323]
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(1,39):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(1,59):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(2,41):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(2,71):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(3,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(4,34):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(4,55):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(5,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(6,38):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(6,61):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(7,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(7,56):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(8,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(8,56):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(9,34):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(9,54):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(10,39):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(11,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(11,62):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(12,37):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(12,64):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(13,32):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(14,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(15,39):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(15,69):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(16,40):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(17,35):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(18,36):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(19,33):
TS2304: Cannot find name 'readonly'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(19,53):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,27):
TS2304: Cannot find name 'as'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,30):
TS2304: Cannot find name 'K'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,40):
TS2693: 'AllEvents' only refers to a type, but is being used as a value here.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,52):
TS2304: Cannot find name 'K'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,56):
TS2693: 'never' only refers to a type, but is being used as a value here.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,64):
TS2693: 'EventHandlerWithoutArgs' only refers to a type, but is being used as a value here.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,88):
TS2304: Cannot find name 'ArgsType'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,98):
TS2304: Cannot find name 'PropsType'.
ERROR in D:/art-hr/node_modules/make-event-props/dist/cjs/index.d.ts(28,108):
TS2304: Cannot find name 'K'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(2,8):
TS2300: Duplicate identifier 'type'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(2,15):
TS2304: Cannot find name 'formatHour'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(2,29):
TS2304: Cannot find name 'defaultFormatHour'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(2,49):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,8):
TS2300: Duplicate identifier 'type'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,15):
TS2304: Cannot find name 'ClassName'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,15):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,26):
TS2304: Cannot find name 'HandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,38):
TS2304: Cannot find name 'HandWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,49):
TS2304: Cannot find name 'MarkLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,61):
TS2304: Cannot find name 'MarkWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,72):
TS2304: Cannot find name 'OppositeHandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(3,93):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(5,17):
TS2304: Cannot find name 'ClassName'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(6,25):
TS2304: Cannot find name 'defaultFormatHour'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(7,22):
TS2304: Cannot find name 'HandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(8,30):
TS2304: Cannot find name 'OppositeHandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(9,21):
TS2304: Cannot find name 'HandWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(10,23):
TS2304: Cannot find name 'MarkLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(11,22):
TS2304: Cannot find name 'MarkWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(13,24):
TS2304: Cannot find name 'HandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(14,32):
TS2304: Cannot find name 'OppositeHandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(15,23):
TS2304: Cannot find name 'HandWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(16,25):
TS2304: Cannot find name 'MarkLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(17,24):
TS2304: Cannot find name 'MarkWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(23,24):
TS2304: Cannot find name 'HandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(24,32):
TS2304: Cannot find name 'OppositeHandLength'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/Clock.d.ts(25,23):
TS2304: Cannot find name 'HandWidth'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/index.d.ts(2,8):
TS2304: Cannot find name 'type'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/index.d.ts(2,15):
TS2304: Cannot find name 'ClockProps'.
ERROR in D:/art-hr/node_modules/react-clock/dist/cjs/index.d.ts(2,28):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/index.d.ts(2,8):
TS2304: Cannot find name 'type'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/index.d.ts(2,15):
TS2304: Cannot find name 'TimePickerProps'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/index.d.ts(2,33):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(4,8):
TS2300: Duplicate identifier 'type'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(4,15):
TS2304: Cannot find name 'ReactNodeArray'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(4,32):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,8):
TS2300: Duplicate identifier 'type'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,15):
TS2304: Cannot find name 'ClassName'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,15):
TS2695: Left side of comma operator is unused and has no side effects.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,26):
TS2304: Cannot find name 'CloseReason'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,39):
TS2304: Cannot find name 'Detail'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,47):
TS2304: Cannot find name 'LooseValue'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,59):
TS2304: Cannot find name 'OpenReason'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,71):
TS2304: Cannot find name 'Value'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(5,79):
TS2304: Cannot find name 'from'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(6,34):
TS2304: Cannot find name 'ReactNodeArray'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(8,19):
TS2304: Cannot find name 'Omit'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(13,17):
TS2304: Cannot find name 'ClassName'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(17,22):
TS2304: Cannot find name 'ClassName'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(29,17):
TS2304: Cannot find name 'Detail'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(36,24):
TS2304: Cannot find name 'Value'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(47,17):
TS2304: Cannot find name 'CloseReason'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(50,17):
TS2304: Cannot find name 'OpenReason'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(52,13):
TS2304: Cannot find name 'LooseValue'.
ERROR in D:/art-hr/node_modules/react-time-picker/dist/cjs/TimePicker.d.ts(53,18):
TS2304: Cannot find name 'Omit'.

**Comment by wojtekmaj** [comment]
Ancient TypeScript version?

**Comment by KrasnovD** [comment]
3.0.1 :(

**Comment by wojtekmaj** [comment]
5 years old 😅 Older than my son! There's your problem. 

Although this version is ridiculously old and I'll definitely not make changes to support it (sorry!), it makes me wonder, perhaps TypeScript with a certain minimum version should be an optional peerDependency so that you would get a warning on such incompatibilities 🤔
