### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by renanz** [wojtekmaj/react-time-picker#33]
TS7016: Could not find a declaration file for module 'react-time-picker'. '/home/user/Desktop/someProject/frontend/node_modules/react-time-picker/dist/entry.js' implicitly has an 'any' type.

**Comment by wojtekmaj** [comment]
Feel free to contribute :)

**Comment by baywet** [comment]
Their are multiple approaches to provide typings:
- externally in the definitively typed repo (not recommended if the owner of the library is willing to add type declarations in the main repo)
- internally manually, we'd have to add .d.ts files for each js/jsx file and manually describe every class/function/constant... (can be time consuming)
- internally automatically. This would require the current repo to switch to typescript. It should be fairly easy given babel is already in use. This approach would generate the js and d.ts files when building the repo. You'd also benefit typescript's language improvements over javascript.

Do you have any preference @wojtekmaj ?

**Comment by wojtekmaj** [comment]
I don't think adding .d.ts files to every file is worth doing - that's a lot of overhead especially when changing internals. Only one component is really exposed in current React-Time-Picker version. Types should be relatively easy to add.

I'm really no expert in TypeScript, but if they are added to this repo, they become my responsibility to keep up to date. Thus, if added to this repo, I need a way to easily verify if they are working correctly and are not missing anything. If there's no way to automate this process so I could be sure, I'd lean towards definitely typed approach.

**Comment by everas7** [comment]
I want to contribute to this library by adding types on DefinitelyTyped.

**Comment by wojtekmaj** [comment]
Please go ahead and do this :) It will be much appreciated.

**Comment by everas7** [comment]
@wojtekmaj I decided to submit a PR to add types for react-clock first. Since I saw that props from this library are passed down to react-clock. This is the link to it: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49022

**Comment by everas7** [comment]
Here is the PR for this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49121

**Comment by everas7** [comment]
@wojtekmaj PR was merged on DefinitelyTyped, so I think this issue can be closed.

**Comment by wojtekmaj** [comment]
Thank you so much!
