### ISSUE TITLE
Hpow to pick 24hr?

### ISSUE THREAD

**Issue by techwithtwin** [wojtekmaj/react-time-picker#346]
Hello, how to pick 24hr

**Comment by tim-rohrer** [comment]
The default behavior per the README is for the system locale to be used. As a test, I've set my locale to GB (I'm in the US), restarted by computer, and confirmed UK is showing in the regional format settings of Gnome 47.0 on Ubuntu 24.10.

![Image](https://github.com/user-attachments/assets/73352c59-c86e-4b97-abf6-24c15bc95099)

My code snippet:

```ts
<TimePicker
  id="startTime"
   name="startTime"
    onChange={(value) => {
      setTime(value ?? getRoundedCurrentTime())
     }}
     value={time}
     disableClock
/>
```
But I keep getting a display using AM/PM:

![Image](https://github.com/user-attachments/assets/bbcc2bfd-7508-4120-add7-bd0a921d1129)

I've tested this on the latest versions of Brave, Chrome and FireFox.

Any ideas what I can try next? I don't want to force a locale for international users.
