### ISSUE TITLE
Height/width/top of hour/minute/second inputs unable to be overridden. (Unable to manually fix styling issue in Microsoft Edge)

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#36]
There is an issue in Microsoft Edge where the width of the inputs for the hour/minutes/seconds is a little bit too narrow to accomodate the width of the digits. Perhaps this is an issue with Edge not properly supporting the calculations that's done in the less file for the styling?

More importantly, I tried overriding the calculated width in my own JSS and it can't be overridden; my styling just keeps getting replaced with the value coming from the react-time-picker.

This doesn't work. I also tried overriding in the hour/minute/second classes and that doesn't work either. (Using `!important` doesn't work either.)
`'& .react-time-picker__inputGroup__input': {
            width: '1.375rem',
}`

I've also tried overriding top and height of the inputs and the styling never persists when I server up my site, it's always overridden by styling coming from the react-time-picker.

![edgetimepickerissue](https://user-images.githubusercontent.com/4451556/60039983-f8c53000-9685-11e9-899c-e695820660db.png)

**Comment by williejay2017** [comment]
This is happening on chrome too (v75) [#39](https://github.com/wojtekmaj/react-time-picker/issues/39)

**Comment by cunningryan** [comment]
I got a report of this happening for Edge on Windows from my test team, but I'm not seeing it on Mac for any of these:
* Edge
* Chrome (v75)
* Safari
* Firefox
* Opera

**Comment by wojtekmaj** [comment]
Hm, that's not something that should be resolved manually with a CSS hack. It's either bug in `update-input-width` *or* you guys are overwriting box-sizing, which is deliberately set to `content-box` for all these inputs.

**Comment by emilyuhde** [comment]
@wojtekmaj I just checked my code again and I'm not overriding `box-sizing` anywhere, so I think it must be a bug. 

I would like to be able to do manual style overrides on the inputs, even if the bug is resolved with the TimePicker though. This is what my styled TimePicker looks like an our UX designer would like the time numbers to be closer to the label that is inside of the box, but I cannot change the `top` position of them.

<img width="313" alt="Screen Shot 2019-07-11 at 2 12 22 PM" src="https://user-images.githubusercontent.com/4451556/61074587-07317c80-a3e6-11e9-8502-d648a95ac2df.png">

**Comment by wojtekmaj** [comment]
I believe this might have been fixed in ad13f61d34d8f9c4b0118ce29de0a9a1a6a7db4e (v3.7.1).
