### ISSUE TITLE
Edge browser: intermittent flicking of blue focus state color on click of an input

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#37]
When using the react-time-picker in Edge, if you click onto one of the inputs (hour, minute, second) the text will highlight in dark blue and then it will quickly disappear and you will see your cursor inside of the input. This does not happen consistently, but it happens often. I belive the dark blue text highlighting is a focus state in Edge. If you go to the dev tools and apply the "focus" artificial state to one of the inputs, you will see the same blue text highlighting appear.

This isn't a major issue, it isn't breaking anything, but it is a little strange looking.

**Comment by wojtekmaj** [comment]
Oh my, you're now a full-time React-Time-Picker tester! 💪 

Would you mind specifying Edge version? I have plenty, and Chromium-based Edge didn't make it any easier :D

**Comment by wojtekmaj** [comment]
Note to self: Likely to be happening in React-Date-Picker too, check & fix everywhere

**Comment by emilyuhde** [comment]
I know, I feel kind of bad filing so many issues!

I see this issue on:
Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299

**Comment by wojtekmaj** [comment]
That's not bad at all! I'm happy to have someone QA-ing my work this actively :) Obviously it's challenging for me to be the judge of my own creations.

Working on 🍎 right now so I will check this issue on Windows in the evening. Thanks!

**Comment by emilyuhde** [comment]
Sounds great, thank you!

I hope I can start contributing some code changes to the repo soon. I've been so busy at work trying to make the TimePicker we're building off of yours, so I've been able to QA it, but not make active code constructions.

**Comment by wojtekmaj** [comment]
Confirmed on Edge 18.
It looks like Edge can't keep selection on re-render, and re-render (showing clock) happens after text selection.

**Comment by wojtekmaj** [comment]
Just a heads-up - React-Time-Picker `v3.6.0` was released a few moments ago and includes the fix for this issue.
