### ISSUE TITLE
Input cutting off values upon initial render.

### ISSUE THREAD

**Issue by williejay2017** [wojtekmaj/react-time-picker#39]
<img width="601" alt="Screen Shot 2019-06-27 at 1 22 53 PM" src="https://user-images.githubusercontent.com/26513346/60290758-117c5280-98df-11e9-884f-e7a7785d3874.png">

The start time input is how it should display, but upon rendering the endtime input is what I get, until I change the time then it corrects itself.

**Comment by wojtekmaj** [comment]
I believe this might have been fixed in ad13f61d34d8f9c4b0118ce29de0a9a1a6a7db4e (v3.7.1).
