### ISSUE TITLE
No maxLength handling for inputs at the end of the component

### ISSUE THREAD

**Issue by Temoto-kun** [wojtekmaj/react-time-picker#45]
For instance, if I disable the seconds on the component, I could input something like `12:333333333` and it will not auto-correct on the input (however, the value is corrected to `12:33`. For inputs with seconds, I could do `12:33:33333333` just fine without the event being blocked.

Kind of related to #15, I think

**Comment by ultrinnan** [comment]
+1 need this functionality...
as a workaround here is part of my onBlur method:
```
stripTime(){
        let hourInputs = document.getElementsByClassName('react-time-picker__inputGroup__hour');
        let minInputs = document.getElementsByClassName('react-time-picker__inputGroup__minute');
        for (let hItem of hourInputs) {
            let hValue = hItem.value;
            hItem.value = Number(hValue) < 24 ? hValue : 23;
        }
        for (let mItem of minInputs) {
            let mValue = mItem.value;
            mItem.value = Number(mValue) < 60 ? mValue : 59;
        }
    }
```

**Comment by venigallapraveen** [comment]
I fixed it by writing this css class:

.react-datetime-picker__inputGroup__second {
    max-width: 20px !important;

}

**Comment by wojtekmaj** [comment]
With 6377396 this should no longer be an issue.
