### ISSUE TITLE
Hour/minute/second inputs accepting `e`, `-` and `+`

### ISSUE THREAD

**Issue by TheoryOfNekomata** [wojtekmaj/react-time-picker#46]
Since the inputs are of type `number`, and the said characters are valid for entering numbers (e.g. `1.234e+23`), the inputs accept such characters.

Should the inputs block those characters for the behavior to be consistent with other invalid characters?

**Comment by wojtekmaj** [comment]
Yeah, we should probably disable that.

**Comment by emilyuhde** [comment]
I also noticed that in v3.6.1 numbers with decimals are handled nicely, except when a 0 follows. For example, my locale is en-US, I enter 1.2 into the TimePicker and the ".2" is parsed off so only a value of 1 shows up on blur of the input. If I enter 1.0 into the input, onblur the .0 is still there. That seems related to it being a type=number input as well. 

Also, I haven't tried it yet, but while this is all being fixed , should be checked too. For example, in Germany , is used the way . is used in the US.

**Comment by wojtekmaj** [comment]
e, -, and + are all not accepted anymore
