### ISSUE TITLE
Suggestion: Add a changelog.md file 

### ISSUE THREAD

**Issue by emilyuhde** [wojtekmaj/react-time-picker#50]
It would be really helpful to have a changelog for the react-time-picker so we can see what updates are made with each version, hopefully with links to closed issues too. Thanks :D

**Comment by wojtekmaj** [comment]
Hi,
all notable changes are tracked in [GitHub releases](https://github.com/wojtekmaj/react-time-picker/releases). :)

**Comment by emilyuhde** [comment]
That works, thanks!
