### ISSUE TITLE
Why not add a callback, let say onInvalid (yes totally stupid), that takes a function receiving the value? Or ...

### ISSUE THREAD

**Issue by jarlah** [wojtekmaj/react-time-picker#58]
I am using this simple dep to select time, and time should always be updated even if its invalid! I need to both show that the field is invalid AND update the value. With this plugin i have to stop using max and min, and calculate whether it is valid or not when rendering. And choosing a red background or text color for the input field.

Is there a work around for always acting on the value even if its invalid?

**Comment by wojtekmaj** [comment]
onInvalid shouldn't be caught so you may catch it in parent element 🤔
