### ISSUE TITLE
onChange always returns string

### ISSUE THREAD

**Issue by jbojcic1** [wojtekmaj/react-time-picker#66]
Since value can be Date or string would it make sense that onChange returns value in whichever format value was using?

So if I pass date, I get the date back and if I pass string I get the string back.

**Comment by wojtekmaj** [comment]
You can get hour from Date(), but you can't get Date() from hour alone. Hence the string returned.

**Comment by jbojcic1** [comment]
Could it work same like https://material-ui-pickers.dev/ does?

There if you pass date to the time picker as value, in onChange you get another date instance where date is same like in the value you provided while time is set based on the values selected in the time picker.

**Comment by jbojcic1** [comment]
In my project I created a wrapper component where I handle formatting and parsing so now my wrapped timepicker can handle Date, timestamp and string. However I needed to add format prop to the component for cases when value is null since then you can't infer which format is needed based on the passed value.

**Comment by wojtekmaj** [comment]
Interesting idea, but not something I'll be looking to implement in the immediate future.
