### ISSUE TITLE
Is there a way to customize the picker?

### ISSUE THREAD

**Issue by Tsabary** [wojtekmaj/react-time-picker#71]
Specifically, is there an option to remove the border/outline?

**Comment by wojtekmaj** [comment]
Of course. Default styling is only a suggestion. You can style it yourself in 3 ways: from the ground up, based on default styling you can find on this repo, or simply overwriting styles you don't like. :)

**Comment by akhilaudable** [comment]
Not finding a way to remove the border
Added this in style. but not working. 

```
import React from 'react';
import TimePicker from 'react-time-picker';
import { withStyles } from '@material-ui/core/styles';

const styles = theme => ({
  '@global': {
    '.react-time-picker__wrapper': {
      border: 'none'
    }
  }
});

export default withStyles(styles)(({ 
  classes,
  onChange,
  value,
  ...others
}) => {

  return (
    <TimePicker
      onChange={onChange}
      value={value}
      {...others}
    />
  );
})




```

**Comment by deborahdiazr** [comment]
Did you figure out how to style it?

**Comment by antonio-hickey** [comment]
In case anyone comes across this and is confused with the answer "simply overwriting yourself":

- inspect the elements to find the specific css class you want to overwrite a attribute of
- create a class in your css file with the same class name and with the attribute value you want

For example: I wanted to remove the border around the picker wrapper, so I inspected the elements found the class that sets the border (in my case `.react-time-picker__wrapper`). Then I added this to my css file to overwrite it's value:
```css
.react-time-picker__wrapper {
  border: none !important;
}
```

Hope this helps some save a bit of thinking haha
