### ISSUE TITLE
react-time-picker issue in IE 11

### ISSUE THREAD

**Issue by damodaram1010** [wojtekmaj/react-time-picker#72]
I am using 'react-time-picker' for time picker in spfx webpart in production, it was working fine. But suddenly it is not rendering correctly from 5th Jan 2020. 

![image](https://user-images.githubusercontent.com/48432247/72214584-47a3bb80-352b-11ea-9ef5-d582b7b15815.png)

**Comment by wojtekmaj** [comment]
Well for starters the date is highly unlikely to break styling, so something else might have happened in your project on January the 5th. Check your repo for changes and dependency updates. Perhaps an update broke something for you.
