### ISSUE TITLE
Impossible to set a cursor position in FireFox

### ISSUE THREAD

**Issue by manhoodofhumanity** [wojtekmaj/react-time-picker#73]
Clicking on hours or minutes does not set a cursor position to there. So we need to clear minutes and then we can change the hours:( 

Is there a possibility to fix this?

**Comment by wojtekmaj** [comment]
I'm unable to reproduce - clicking on hours/minutes/seconds selects the whole input as designed.

I even develop this thing mainly on Firefox... :P

**Comment by wojtekmaj** [comment]
Can you be more specific? What are exactly your actions and what exactly does not work?

**Comment by manhoodofhumanity** [comment]
My bad... Everything works fine. Sorry)
