### ISSUE TITLE
minTime and maxTime doesn't work...

### ISSUE THREAD

**Issue by bluego78** [wojtekmaj/react-time-picker#75]
minTime and maxTime doesn't work...
if you set a new Date() or a string like "07:00:00" not working.

**Comment by anniekfifer** [comment]
Also experiencing this issue as of recently but not sure for how long. Reproduced using both Date and string inputs, in military format with and without seconds.

**Comment by toto22450** [comment]
Is there any update on this issue ?

**Comment by eglorenzana** [comment]
I also have this issue.

**Comment by marcosilvestroni** [comment]
as @eglorenzana reported this bug cannot intercept the error why not add an onError callback? for manage this situation?
