### ISSUE TITLE
Incorrect Timezone

### ISSUE THREAD

**Issue by Kahnox** [wojtekmaj/react-time-picker#76]
GMT+0200 (Summertime) is used instead of GMT+0100 (Normaltime). Is there some way to disable daylight saving time?

**Comment by wojtekmaj** [comment]
React-Time-Picker doesn't do any timezone conversions, it simply returns local time much like native time picker on modern browsers do. If you see GMT+0200 must be a result of some conversion to Date() object, which, by default, when stringified, returns a date in your local timezone.

**Comment by Kahnox** [comment]
Found the mistake in my code, my bad. Thank you!
