### ISSUE TITLE
Minutes and seconds fields allow numbers with more than two digits

### ISSUE THREAD

**Issue by matteovinci** [wojtekmaj/react-time-picker#78]
User should not be able to insert a value greater than `59` in minutes/seconds fields.
<img width="1440" alt="Screen Shot 2020-03-11 at 3 04 26 PM" src="https://user-images.githubusercontent.com/827135/76468750-f0df2480-63a9-11ea-9c87-e3b1816a8883.png">

**Comment by wojtekmaj** [comment]
Demo page was not updated (until now), but preventing the user from writing too long values has been implemented.

**Comment by matteovinci** [comment]
Thanks for handling this quick!
