### ISSUE TITLE
Clock not updating on click

### ISSUE THREAD

**Issue by gopinath-sixt** [wojtekmaj/react-time-picker#8]
Hi,

When i click on the clock, time not updating in the input box. 

is it, clock for only display or it will trigger changes when clicking on the clock.

Thanks

**Comment by wojtekmaj** [comment]
Hello,
Clock is for display only.

**Comment by gopinath-sixt** [comment]
Thank for your message!!!

**Comment by montogeek** [comment]
Sorry for hijacking this bug, It is possible to update the clock while you update the time? Like in realtime?

**Comment by wojtekmaj** [comment]
[React-Clock](/wojtekmaj/react-clock) which is used here allows that. but we close the controls every time a valid input is selected. We could take into consideration not to close it.
