### ISSUE TITLE
Build error due to src/ folder

### ISSUE THREAD

**Issue by pkang1** [wojtekmaj/react-time-picker#86]
I have one repo (let's call it Repo 1) that includes custom react component built which also use third party components available. Once built this whole repo is used as one npm package in another repo (Repo). The problem I am experiencing is inside Repo 2 build. **Once I manually delete "src" folder from Repo 1 node_modules/react-time-picker - everything works fine.** Is there any use of "src" for users of this package?

Here is the error I am getting:

 [....]\node_modules\react-time-picker\src\entry.js
Cannot resolve dependency './TimePicker.css' at '[....]\node_modules\react-time-picker\src\TimePicker.css'
   5 | // File is created during build phase and placed in dist directory
   6 | // eslint-disable-next-line import/no-unresolved
>  7 | import './TimePicker.css';
     |       ^
   8 | 
   9 | export default TimePicker;
  10 |

**Comment by wojtekmaj** [comment]
You're not supposed to import pacakge's `src` folder.
