### ISSUE TITLE
How to disable <Clock/> component?

### ISSUE THREAD

**Issue by ivanfr90** [wojtekmaj/react-time-picker#9]
Hi!

There are any posibility to disable the display of the clock component when pick into input? I need to use only the input.

I've tried with the following props without lucky  
```
isOpen={false}
clockIcon={null}
```

Thanks!

**Comment by wojtekmaj** [comment]
Hello,
for the moment it's not possible - I'd use

```css
.react-time-picker__clock { display: none; }
```

as a workaround. I'll keep your suggestion in mind though!
```

**Comment by wojtekmaj** [comment]
Hi @ivanfr90, starting with v2.6.1 you can use `disableClock` prop.
