### ISSUE TITLE
How to change text inside option in select "am, pm" 

### ISSUE THREAD

**Issue by candrescastel** [wojtekmaj/react-time-picker#95]
Actual text is **a.&nbsp;m.** an i just want AM

**Comment by wojtekmaj** [comment]
text inside depends on locale and is based on browser's date formatting for a given locale.

For example, on Firefox, en-US locale gives:

```js
> Intl.DateTimeFormat('en-US', { hour: 'numeric' }).format(new Date(2020, 0, 1, 9));
< "9 AM"

> Intl.DateTimeFormat('en-US', { hour: 'numeric' }).format(new Date(2020, 0, 1, 21));
< "9 PM"
```

which would result in "AM" and "PM" options in dropdown.
