### ISSUE TITLE
Handle paste and copy better

### ISSUE THREAD

**Issue by ccnokes** [wojtekmaj/react-time-picker#96]
I was thinking it'd be nice if when you pasted into a field a string like `10:15`, it would parse it and set the hour and minute fields accordingly. Likewise, when you copied from any field, it grabbed the formatted time value instead of the individual field you happened to have focused and copied from. I think users conceptually think of the time field as a single input rather than a combination of hours + minutes inputs, so I think that change accommodates that mental model better and could provide a better UX. 

I'd be happy to PR that if it's something you'd be ok with adding in. ❤️  this library btw, good work!

**Comment by wojtekmaj** [comment]
That would be really awesome! I'd love to see your PR, and I could work on it a little more if needed.
